package com.splitly.model;

public enum ActivityType {
    USER_JOINED_GROUP,
    USER_LEFT_GROUP,
    EXPENSE_ADDED,
    EXPENSE_UPDATED,
    EXPENSE_DELETED,
    SETTLEMENT_INITIATED,
    SETTLEMENT_CONFIRMED,
    GROUP_CREATED,
    GROUP_UPDATED,
    MEMBER_INVITED,
    MEMBER_REMOVED
}
